from EMPIRICAL_ESTIMATES import main_EMPIRICAL_ESTIMATES_train_single_ANN_remapping

if __name__ == '__main__':
    main_EMPIRICAL_ESTIMATES_train_single_ANN_remapping.main_EMPIRICAL_ESTIMATES_train_single_ANN_remapping()
