from EXP_G_VULN_MULTIPLE_GUESSES import main_EXP_G_VULN_MULTIPLE_GUESSES_create_g_matrix

if __name__ == '__main__':
    main_EXP_G_VULN_MULTIPLE_GUESSES_create_g_matrix.main_EXP_G_VULN_MULTIPLE_GUESSES_create_g_matrix()
