from EXP_G_VULN_MULTIPLE_GUESSES import main_EXP_G_VULN_MULTIPLE_GUESSES_train_single_ANN_remapping

if __name__ == '__main__':
    main_EXP_G_VULN_MULTIPLE_GUESSES_train_single_ANN_remapping.main_EXP_G_VULN_MULTIPLE_GUESSES_train_single_ANN_remapping()
