from EXP_G_VULN_MULTIPLE_GUESSES import main_EXP_G_VULN_MULTIPLE_GUESSES_compute_g_vuln_star

if __name__ == '__main__':
    main_EXP_G_VULN_MULTIPLE_GUESSES_compute_g_vuln_star.main_EXP_G_VULN_MULTIPLE_GUESSES_compute_g_vuln_star()
