from EXP_G_VULN_GEO_LOCATION import main_EXP_G_VULN_GEO_LOCATION_get_stats_from_classifiers

if __name__ == '__main__':
    main_EXP_G_VULN_GEO_LOCATION_get_stats_from_classifiers.main_EXP_G_VULN_GEO_LOCATION_get_stats_from_classifiers()
