from EXP_G_VULN_GEO_LOCATION import main_EXP_G_VULN_GEO_LOCATION_train_single_ANN_remapping

if __name__ == '__main__':
    main_EXP_G_VULN_GEO_LOCATION_train_single_ANN_remapping.main_EXP_G_VULN_GEO_LOCATION_train_single_ANN_remapping()
