from BIS_EXP_G_VULN_GEO_LOCATION import main_BIS_EXP_G_VULN_GEO_LOCATION_evaluate_ANN_remapping

if __name__ == '__main__':
    main_BIS_EXP_G_VULN_GEO_LOCATION_evaluate_ANN_remapping.main_EXP_G_VULN_GEO_LOCATION_evaluate_ANN_remapping()
