from EXP_GEO_LOCATION_QIF_LIB_SETTING import main_EXP_GEO_LOCATION_QIF_LIB_SETTING_create_channel_and_g_mat_and_data
from EXP_GEO_LOCATION_QIF_LIB_SETTING import main_EXP_GEO_LOCATION_QIF_LIB_SETTING_retrieve_data_from_DB


def main_EXP_GEO_LOCATION_QIF_LIB_SETTING_wrapper():
    # main_EXP_GEO_LOCATION_QIF_LIB_SETTING_retrieve_data_from_DB.main_EXP_GEO_LOCATION_QIF_LIB_SETTING_retrieve_data_from_DB()
    main_EXP_GEO_LOCATION_QIF_LIB_SETTING_create_channel_and_g_mat_and_data.main_EXP_GEO_LOCATION_QIF_LIB_SETTING_create_channel_and_g_mat_and_data()


if __name__ == '__main__':
    main_EXP_GEO_LOCATION_QIF_LIB_SETTING_wrapper()
