# from main_EMPIRICAL_ESTIMATES_compute_empirical_estimate_wrapper import main_EMPIRICAL_ESTIMATES_compute_empirical_estimate
# from EXP_GEO_LOCATION_QIF_LIB_SETTING import main_EXP_GEO_LOCATION_QIF_LIB_SETTING_retrieve_data_from_DB
# from EXP_GEO_LOCATION_QIF_LIB_SETTING import main_EXP_GEO_LOCATION_QIF_LIB_SETTING_create_channel_and_g_mat_and_data
# from EXP_G_VULN_DP import main_EXP_G_VULN_DP_create_channel_and_g_mat_and_data
# from main_BIS_EXP_G_VULN_MULTIPLE_GUESSES_create_channel_and_data_wrapper import \
#    main_BIS_EXP_G_VULN_MULTIPLE_GUESSES_create_channel_and_data_wrapper
# from BIS_EXP_GEO_LOCATION_QIF_LIB_SETTING import main_BIS_EXP_GEO_LOCATION_create_channel_and_data
from utilities_pckg import check_training_sets_sizes

# from BIS_EXP_G_VULN_DP import main_BIS_EXP_G_VULN_DP_create_channel_and_g_mat_and_data

# main_EMPIRICAL_ESTIMATES_compute_empirical_estimate.main_COMPUTE_ESTIMATES_compute_estimate()
# main_EXP_GEO_LOCATION_QIF_LIB_SETTING_retrieve_data_from_DB.main_EXP_GEO_LOCATION_QIF_LIB_SETTING_retrieve_data_from_DB()
# main_EXP_GEO_LOCATION_QIF_LIB_SETTING_create_channel_and_g_mat_and_data.main_EXP_GEO_LOCATION_QIF_LIB_SETTING_create_channel_and_g_mat_and_data()
# main_EXP_G_VULN_DP_create_channel_and_g_mat_and_data.main_EXP_G_VULN_DP_create_channel_and_g_mat_and_data()
# main_BIS_EXP_G_VULN_MULTIPLE_GUESSES_create_channel_and_data_wrapper()
# main_BIS_EXP_GEO_LOCATION_create_channel_and_data.main_BIS_EXP_GEO_LOCATION_create_channel_and_data()
# main_BIS_EXP_G_VULN_DP_create_channel_and_g_mat_and_data.main_BIS_EXP_G_VULN_DP_create_channel_and_g_mat_and_data()

check_training_sets_sizes.main_check_training_sets_sizes()
