from EXP_G_VULN_DP import main_EXP_G_VULN_DP_create_channel_and_g_mat_and_data

if __name__ == '__main__':
    main_EXP_G_VULN_DP_create_channel_and_g_mat_and_data.main_EXP_G_VULN_DP_create_channel_and_g_mat_and_data()
